# To be used in Portainer

version: "3.9"

volumes:
  db_data:
    driver: local

services:
  db:
    image: "postgres:14"
    restart: unless-stopped
    env_file:
      - "stack.env"
    environment:
      PGUSER: "loki"
      PGPASSWORD: "loki"
      PGDATABASE: "loki"
      POSTGRES_USER: "loki"
      POSTGRES_PASSWORD: "loki"
      POSTGRES_DB: "loki"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "db_data:/var/lib/postgresql/data"

  web:
    image: "ghcr.io/steffo99/lokiunimore:latest"
    command: >-
      gunicorn 
      -b 0.0.0.0:30035 
      lokiunimore.web.app:rp_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:30035:30035"
    env_file:
      - "stack.env"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://loki:loki@db/loki"
    depends_on:
      db:
        condition: service_healthy

  bot:
    image: "ghcr.io/steffo99/lokiunimore:latest"
    command: >- 
      lokiunimore.matrix
    restart: unless-stopped
    env_file:
      - "stack.env"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://loki:loki@db/loki"
    depends_on:
      db:
        condition: service_healthy
